version: 1
quotes:
  - "'Scrum is like your mother-in-law, it points out ALL your faults.' - Ken Schwaber"
  - "'Working software over comprehensive documentation' - Manifesto for Agile Software Development"
  - "'In summary: Lean leaders lead, rather than follow, a Lean-Agile transformation.<br /> Such a responsibility cannot be delegated.' - Dean Leffingwell"
  - "'Customer collaboration over contract negotiation' - Manifesto for Agile Software Development"
  - "'We don't need an accurate document. We need a shared understanding.' - Jeff Patton"
  - "'If you are not yet an expert in a subject matter (e.g. Scrum) do not attempt to adapt it.<br /> Scrum is an adaptive process. But you are in no position to adapt it until you know it well, and have experienced it in operation.' - Ken Schwaber"
  - "'Stable Velocity. Sustainable Pace.' - Mike Cottmeyer"
  - "'Stop focusing on Projects and focus instead on creating stable, sustainable teams.' - Richard Dolman"
  - "'Lean is all about running experiments and minimizing risk. Be a scientist, run an experiment.' - Tami Reiss"
  - "'Individuals and interactions over processes and tools' - Manifesto for Agile Software Development"
  - "'Responding to change over following a plan' - Manifesto for Agile Software Development"
  - "'if you cannot fail, you cannot learn.' - Eric Ries"
  - "'Life's too short to build something nobody wants.' - Ash Maurya, Running Lean"
  - "'In a startup, both the problem and the solution are unknown.' - Eric Ries"



  