version: 1

formatters:
  simple:
    format: '[%(asctime)s - %(name)s:%(levelname)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  rotatingFile:
    class: logging.handlers.TimedRotatingFileHandler
    filename: SignOffRotator.log
    when: midnight
    level: DEBUG
    formatter: simple
loggers:
  SignOffRotator:
    level: DEBUG
    handlers: [console, rotatingFile]
    propagate: no
  SignOffRotatorTest:
    level: DEBUG
    handlers: [console, rotatingFile]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
